# sel test

In [1]:
# Convenient jupyter setup
%load_ext autoreload
%autoreload 2
%config IPCompleter.greedy=True

In [8]:
import os

In [40]:
from src.constants import KAT_EX_PATH, NO_BBOX, NEW_ORLEANS

In [2]:
from src.preprocessing.sel import trim_tri

In [3]:
?trim_tri

In [4]:
from adcircpy.outputs import Fort63

In [9]:
f63 = Fort63(os.path.join(KAT_EX_PATH, "fort.63.nc"))

In [10]:
f63.y

array([39.31352665, 39.30541742, 45.69340656, ..., 15.86675545,
       15.84477831, 15.75183811])

In [11]:
trim_tri

<function src.preprocessing.sel.trim_tri(x: numpy.ndarray, y: numpy.ndarray, tri: numpy.ndarray, bbox: sithom.place.BoundingBox, z: Union[numpy.ndarray, NoneType] = None) -> Union[Tuple[numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray], Tuple[numpy.ndarray, numpy.ndarray, numpy.ndarray]]>

In [19]:
f63._ptr["zeta"][:].shape

(252, 8303)

In [44]:
x, y, tri, z = trim_tri(f63.x, f63.y, f63.triangles, NEW_ORLEANS.bbox(3), f63._ptr["zeta"][:])

In [46]:
import xarray as xr

In [ ]:
xr.Dataset()

In [21]:
f63.triangles

array([[5188, 5433, 5189],
       [7844, 7776, 7843],
       [4550, 4805, 4806],
       ...,
       [ 996, 1078, 1077],
       [ 995, 1077, 1076],
       [1078, 1167, 1077]], dtype=int32)

In [48]:
import matplotlib.pyplot as plt
from sithom.plot import plot_defaults

In [78]:
from src.constants import FIGURE_PATH
plot_defaults()
vmin=-3.75
vmax=3.75
levels = np.linspace(vmin, vmax, num=400)
figs_path = os.path.join(FIGURE_PATH, "katrina_hit")
# os.mkdir(figs_path)


def make_part(num=125):
    plt.tricontourf(x, y, tri, z.data[num], vmin=vmin, vmax=vmax, levels=levels, cmap="cmo.balance")
    plt.colorbar(label="Height [m]")
    plt.xlabel("Longitude [$^{\circ}$E]")
    plt.ylabel("Latitude [$^{\circ}$N]")
    plt.savefig(os.path.join(figs_path, str(num) + ".png"))
    plt.clf()

#make_part(200)
#plt.show()
#make_part(206)
#plt.show()
for i in range(z.shape[0]):
    make_part(i)

<Figure size 826.772x510.973 with 0 Axes>

In [79]:
fig_paths = [os.path.join(figs_path, str(num) + ".png") for num in range(z.shape[0])]
import imageio
ims = [imageio.imread(f) for f in fig_paths]
imageio.mimwrite(os.path.join(FIGURE_PATH,"katrina_hit.gif"), ims)

/var/folders/q5/n7rv_91d6b58cbb5xkzlsc4c0000gn/T/ipykernel_79592/1050790239.py:3: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  ims = [imageio.imread(f) for f in fig_paths]


In [43]:
NEW_ORLEANS.bbox(3)

[('Latitude bounds', [26.9511, 32.9511], 'degrees_north'), ('Longitude bounds', [-93.0715, -87.0715], 'degrees_east'), 'Bounding Box around point: New Orleans Point']

In [54]:
z.min(), z.max()

(-0.9199999999999999, 3.6469334306501096)

In [61]:
vmin=-3.75
vmax=3.75
levels = np.linspace(vmin, vmax, num=400)
import numpy as np

In [77]:
z.data

array([[-2.48405040e-05, -1.52187881e-05, -4.26740139e-06, ...,
         1.64582711e-04,  1.05632111e-04,  5.77992435e-05],
       [-1.28604553e-05, -1.01544597e-04, -1.19852083e-04, ...,
         3.84890470e-04,  2.19018973e-04,  1.59168814e-04],
       [ 8.20444799e-05, -1.44906312e-04, -2.97147353e-04, ...,
        -1.09441751e-03, -1.29712642e-03, -1.30199395e-03],
       ...,
       [ 3.32145416e-01,  3.32902838e-01,  3.32894626e-01, ...,
        -1.71627514e-01, -1.60826919e-01, -1.59862537e-01],
       [ 3.31974155e-01,  3.26307517e-01,  3.27281998e-01, ...,
        -1.97586021e-01, -1.89927248e-01, -1.91961792e-01],
       [ 3.27634117e-01,  3.15172088e-01,  3.21221119e-01, ...,
        -2.02236854e-01, -1.98990330e-01, -2.04719499e-01]])