# Trieste

In [1]:
# Convenient jupyter setup
%load_ext autoreload
%autoreload 2
%config IPCompleter.greedy=True

In [2]:
import os
from omegaconf import OmegaConf
from src.constants import CONFIG_PATH
from sithom.plot import plot_defaults
plot_defaults()

## Is tensorflow working?

In [3]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

2023-06-26 13:53:29.417573: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


TensorFlow version: 2.11.1


In [4]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 [==============================] - 1s 0us/step


In [5]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

2023-06-26 13:54:00.291513: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [6]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.73798996,  0.22071701,  0.02221102, -0.45886058,  0.56066203,
        -0.13482471, -0.3572015 ,  0.5459094 ,  0.91837835,  0.04039938]],
      dtype=float32)

In [7]:
tf.nn.softmax(predictions).numpy()


array([[0.03991444, 0.1041097 , 0.08536524, 0.05276602, 0.14626062,
        0.07295942, 0.05841231, 0.14411873, 0.20916145, 0.08693211]],
      dtype=float32)

In [9]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)


In [10]:
loss_fn(y_train[:1], predictions).numpy()


2.617852

In [11]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [12]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.3030 - accuracy: 0.9117
Epoch 2/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.1469 - accuracy: 0.9563
Epoch 3/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.1105 - accuracy: 0.9666
Epoch 4/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0919 - accuracy: 0.9717
Epoch 5/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0777 - accuracy: 0.9760


In [13]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0796 - accuracy: 0.9766 - 288ms/epoch - 920us/step


[0.07959438115358353, 0.9765999913215637]

In [14]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [15]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.2334969e-07, 2.5109698e-10, 3.2966866e-05, 4.8035403e-05,
        4.5576446e-12, 9.8782618e-07, 3.1706591e-14, 9.9990535e-01,
        1.1319307e-06, 1.1420937e-05],
       [4.4968279e-10, 3.6090656e-05, 9.9995553e-01, 5.9935701e-07,
        6.1455048e-15, 4.8618044e-06, 7.8038971e-07, 7.1551465e-15,
        1.9968757e-06, 6.1463170e-14],
       [4.5567287e-08, 9.9900275e-01, 3.4027611e-04, 2.5465529e-06,
        4.3112774e-05, 1.5258771e-05, 2.3079005e-05, 4.3566659e-04,
        1.3673786e-04, 5.4023110e-07],
       [9.9993801e-01, 2.3734875e-10, 9.2425662e-06, 1.9217261e-08,
        7.8068565e-09, 4.3139264e-07, 5.1303465e-05, 4.7506896e-07,
        1.4495763e-09, 5.2287498e-07],
       [2.3489240e-06, 4.8111615e-11, 4.9797050e-06, 1.6807194e-07,
        9.9884319e-01, 3.3102603e-07, 1.3200348e-07, 2.4360146e-05,
        4.9283381e-07, 1.1239263e-03]], dtype=float32)>

## Now try trieste

In [ ]:
import trieste
print("Trieste version:" )

In [18]:
import numpy as np
import tensorflow as tf

np.random.seed(1793)
tf.random.set_seed(1793)

In [21]:
from trieste.objectives import ScaledBranin
from trieste.experimental.plotting import plot_function_plotly
from trieste.space import Box

scaled_branin = ScaledBranin.objective
search_space = ScaledBranin.search_space  # predefined search space
search_space = Box([0, 0], [1, 1])  # define the search space directly

fig = plot_function_plotly(
    scaled_branin,
    search_space.lower,
    search_space.upper,
    grid_density=20,
)
fig.update_layout(height=400, width=400)
fig.show()

ValueError: Index data must be 1-dimensional

In [17]:
import trieste
print(trieste.__version__)

1.1.2


In [ ]:
print("Ok")

In [ ]:
import trieste


In [ ]:
import tensorflow as tf